site_name: DataDisAggregation
repo_url: https://github.com/wingechr/data-disaggregation

# Configuration
theme:
  name: material
  locale: en
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.indexes
    #- navigation.path
    #- navigation.tracking
    #- navigation.footer
    #- navigation.top
    #- toc.follow
    #- search.suggest
    #- search.share

# Extensions
markdown_extensions:
  #- admonition
  #- attr_list
  #- def_list
  #- md_in_html
  #- pymdownx.details
  #- pymdownx.superfences

plugins:
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: true
            docstring_style: numpy
  - search:
      lang: en
