site_name: DataDisAggregation
repo_url: https://github.com/wingechr/data-disaggregation

# Configuration
theme:
  name: material
  locale: en

# Extensions
markdown_extensions:
  # to include README as a snippet
  - pymdownx.snippets:
      base_path: !relative $config_dir

plugins:
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: true
            docstring_style: numpy
  - search:
      lang: en
