name: test

on:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
      - run: |
          conda install -q -y -c conda-forge tox
          conda create -q -y -n py37 python=3.7
          conda create -q -y -n py311 python=3.11
      - run: |
          export PY37_PATH=$CONDA/envs/py37/bin
          export PY311_PATH=$CONDA/envs/py311/bin
          export PATH=$PATH:$PY37_PATH:$PY311_PATH
          conda run tox # --parallel
