name: test

on:
  push:
    branches:
      - dev

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install uv
          uv sync --group=test
      - run: |
          uv run tox

  codecov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install uv
          uv sync --group=test
      - run: |
          uv run pytest --cov=datatools --cov-report=term-missing --cov-report=xml:coverage.xml
      - uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
